In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns

In [121]:
data = pd.read_csv("Telco_Customer_Churn.csv")

data.head()

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  Female              0     Yes         No       1           No   
1    Male              0      No         No      34          Yes   
2    Male              0      No         No       2          Yes   
3    Male              0      No         No      45           No   
4  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0  No phone service             DSL             No          Yes   
1                No             DSL            Yes           No   
2                No             DSL            Yes          Yes   
3  No phone service             DSL            Yes           No   
4                No     Fiber optic             No           No   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month   
1              Yes          No          No              No        One year   
2               No          No          No              No  Month-to-month   
3              Yes         Yes          No              No        One year   
4               No          No          No              No  Month-to-month   

  PaperlessBilling              PaymentMethod  MonthlyCharges  TotalCharges  \
0              Yes           Electronic check           29.85         29.85   
1               No               Mailed check           56.95       1889.50   
2              Yes               Mailed check           53.85        108.15   
3               No  Bank transfer (automatic)           42.30       1840.75   
4              Yes           Electronic check           70.70        151.65   

  Churn  
0    No  
1    No  
2   Yes  
3    No  
4   Yes

In [4]:
data.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [111]:
print(data["gender"].unique())
print(data["MultipleLines"].unique())
print(data["InternetService"].unique())
print(data["OnlineSecurity"].unique())
print(data["OnlineBackup"].unique())
print(data["DeviceProtection"].unique())
print(data["TechSupport"].unique())
print(data["StreamingTV"].unique())
print(data["StreamingMovies"].unique())
print(data["Contract"].unique())
print(data["PaperlessBilling"].unique())
print(data["PaymentMethod"].unique())
print(data["Churn"].unique())

['Female' 'Male']
['No phone service' 'No' 'Yes']
['DSL' 'Fiber optic' 'No']
['No' 'Yes' 'No internet service']
['Yes' 'No' 'No internet service']
['No' 'Yes' 'No internet service']
['No' 'Yes' 'No internet service']
['No' 'Yes' 'No internet service']
['No' 'Yes' 'No internet service']
['Month-to-month' 'One year' 'Two year']
['Yes' 'No']
['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
['No' 'Yes']


In [122]:
data["gender"].replace(["Female","Male"], [0,1], inplace = True)
data["Partner"].replace(["Yes","No"], [1,0], inplace=True)
data["Dependents"].replace(["Yes","No"], [1,0], inplace=True)
data["PhoneService"].replace(["Yes","No"], [1,0], inplace=True)
data["MultipleLines"].replace(["No phone service","No","Yes"], [0,0,1], inplace=True)
data["InternetService"].replace(["DSL","Fiber optic","No"],[1,2,0], inplace=True)
data["OnlineSecurity"].replace(["No","Yes","No internet service"], [0,1,0],inplace=True)
data["OnlineBackup"].replace(["No","Yes","No internet service"], [0,1,0],inplace=True)
data["DeviceProtection"].replace(["No","Yes","No internet service"], [0,1,0],inplace=True)
data["TechSupport"].replace(["No","Yes","No internet service"], [0,1,0],inplace=True)
data["StreamingTV"].replace(["No","Yes","No internet service"], [0,1,0],inplace=True)
data["StreamingMovies"].replace(["No","Yes","No internet service"], [0,1,0],inplace=True)
data["Contract"].replace(["Month-to-month", "One year", "Two year"], [0,1,2], inplace=True)
data["PaperlessBilling"].replace(["Yes","No"], [1,0], inplace=True)
data["PaymentMethod"].replace(['Electronic check', 'Mailed check' ,'Bank transfer (automatic)',
 'Credit card (automatic)'], [0,1,2,3], inplace=True)
data["Churn"].replace(["Yes","No"], [1,0], inplace=True)

In [123]:
data.head()

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0       0              0        1           0       1             0   
1       1              0        0           0      34             1   
2       1              0        0           0       2             1   
3       1              0        0           0      45             0   
4       0              0        0           0       2             1   

   MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
0              0                1               0             1   
1              0                1               1             0   
2              0                1               1             1   
3              0                1               1             0   
4              0                2               0             0   

   DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0                 0            0            0                0         0   
1                 1            0            0                0         1   
2                 0            0            0                0         0   
3                 1            1            0                0         1   
4                 0            0            0                0         0   

   PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  Churn  
0                 1              0           29.85         29.85      0  
1                 0              1           56.95       1889.50      0  
2                 1              1           53.85        108.15      1  
3                 0              2           42.30       1840.75      0  
4                 1              0           70.70        151.65      1

In [124]:
y = data["Churn"].values
x = data.drop(columns=["Churn"])

In [125]:

from sklearn.preprocessing import MinMaxScaler
features = x.columns.values
scaler = MinMaxScaler(feature_range = (0,1))
scaler.fit(x)
x = pd.DataFrame(scaler.transform(x))
x.columns = features

In [126]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=101)

In [127]:
X_train

gender  SeniorCitizen  Partner  Dependents    tenure  PhoneService  \
2785     0.0            0.0      0.0         0.0  0.690141           1.0   
896      0.0            0.0      0.0         0.0  0.154930           1.0   
3958     0.0            1.0      1.0         0.0  0.718310           1.0   
5193     1.0            0.0      0.0         0.0  0.112676           1.0   
1270     0.0            0.0      1.0         1.0  0.859155           1.0   
...      ...            ...      ...         ...       ...           ...   
599      1.0            0.0      0.0         0.0  0.211268           1.0   
5695     0.0            0.0      1.0         0.0  0.253521           1.0   
1361     1.0            0.0      1.0         0.0  0.126761           1.0   
1547     0.0            0.0      1.0         1.0  0.422535           1.0   
4959     0.0            0.0      0.0         0.0  0.028169           1.0   

      MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
2785            1.0              1.0             1.0           1.0   
896             0.0              1.0             1.0           0.0   
3958            1.0              1.0             0.0           1.0   
5193            0.0              0.0             0.0           0.0   
1270            1.0              1.0             1.0           0.0   
...             ...              ...             ...           ...   
599             0.0              1.0             0.0           0.0   
5695            1.0              1.0             0.0           0.0   
1361            1.0              1.0             0.0           0.0   
1547            1.0              0.5             0.0           1.0   
4959            1.0              0.5             0.0           0.0   

      DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
2785               0.0          1.0          1.0              1.0       1.0   
896                0.0          1.0          1.0              1.0       0.0   
3958               1.0          0.0          1.0              1.0       0.5   
5193               0.0          0.0          0.0              0.0       0.5   
1270               0.0          0.0          1.0              1.0       1.0   
...                ...          ...          ...              ...       ...   
599                0.0          1.0          0.0              0.0       0.0   
5695               0.0          0.0          1.0              0.0       0.0   
1361               0.0          0.0          1.0              0.0       0.0   
1547               0.0          1.0          1.0              1.0       1.0   
4959               0.0          1.0          1.0              0.0       0.0   

      PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  
2785               1.0       0.000000        0.909453      0.638397  
896                1.0       0.666667        0.802488      0.127181  
3958               1.0       0.000000        0.878109      0.646556  
5193               1.0       0.000000        0.016418      0.016824  
1270               1.0       0.666667        0.824876      0.763853  
...                ...            ...             ...           ...  
599                1.0       1.000000        0.560199      0.132899  
5695               1.0       0.000000        0.682587      0.178352  
1361               1.0       0.000000        0.670149      0.091744  
1547               0.0       0.666667        0.619900      0.283037  
4959               1.0       0.000000        0.451244      0.015792  

[4922 rows x 19 columns]

# SVM LINEAR

In [128]:
from sklearn.svm import SVC
clf = SVC(kernel = "linear", random_state=0)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [129]:
y_pred

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [55]:
classifier.support_vectors_

array([[1.        , 0.71830986, 0.87810945, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.11267606, 0.41044776, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.01144279, ..., 0.        , 0.        ,
        1.        ],
       ...,
       [1.        , 0.12676056, 0.54328358, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.51393035, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.02816901, 0.45124378, ..., 0.        , 1.        ,
        0.        ]])

In [56]:
classifier.coef_

array([[ 0.18530778, -1.04954731, -0.33917504, -1.75886957,  0.02120029,
        -0.02120029, -0.0218394 ,  0.0218394 ,  0.04153088, -0.04153088,
         0.05261524, -0.05261524, -0.11666885,  0.05261524,  0.06405361,
        -0.66467759,  0.76154314, -0.09686555,  0.16155819, -0.09686555,
        -0.06469264,  0.07115685, -0.09686555,  0.0257087 ,  0.0339663 ,
        -0.09686555,  0.06289925,  0.17201723, -0.09686555, -0.07515168,
        -0.07280912, -0.09686555,  0.16967467, -0.06630595, -0.09686555,
         0.1631715 ,  0.18792805, -0.17172784, -0.01620021, -0.0757837 ,
         0.0757837 , -0.05527358, -0.11108593,  0.18851659, -0.02215708]])

In [130]:
from sklearn import metrics

print("Accuracy: ", metrics.accuracy_score(y_test, y_pred))

Accuracy:  0.8037914691943128


In [131]:
print("Precision: ", metrics.precision_score(y_test,y_pred))

print("Recall: ", metrics.recall_score(y_test,y_pred))

Precision:  0.6271929824561403
Recall:  0.539622641509434


In [132]:
print("Classification Report for SVM:", metrics.classification_report(y_test,y_pred))

Classification Report for SVM:               precision    recall  f1-score   support

           0       0.85      0.89      0.87      1580
           1       0.63      0.54      0.58       530

    accuracy                           0.80      2110
   macro avg       0.74      0.72      0.73      2110
weighted avg       0.80      0.80      0.80      2110



# SVM rbf model

In [133]:
from sklearn.svm import SVC

clf_kernerl_rbf =  SVC(kernel = "rbf",random_state = 1)
clf_kernerl_rbf.fit(X_train, y_train)
y_pred = clf_kernerl_rbf.predict(X_test)

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8071090047393364


In [134]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8071090047393364


In [135]:
print("Precision: ", metrics.precision_score(y_test,y_pred))

print("Recall: ", metrics.recall_score(y_test,y_pred))

Precision:  0.6597402597402597
Recall:  0.47924528301886793


In [136]:
print("Classification Report for SVM:", metrics.classification_report(y_test,y_pred))

Classification Report for SVM:               precision    recall  f1-score   support

           0       0.84      0.92      0.88      1580
           1       0.66      0.48      0.56       530

    accuracy                           0.81      2110
   macro avg       0.75      0.70      0.72      2110
weighted avg       0.79      0.81      0.80      2110



# Optimal hyperplane

In [137]:
from sklearn.model_selection import GridSearchCV

parameters = [{'C':[1,10,100,1000], 'kernel':['linear']},
              {'C':[1,10,100,1000], 'kernel':['rbf'], 'gamma':[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}
             ]


grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search = grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_

In [138]:
print("Best Accuracy : " + str(best_accuracy))
print("Best Parameters : " + str(best_parameters))

Best Accuracy : 0.798456026649516
Best Parameters : {'C': 1, 'gamma': 0.1, 'kernel': 'rbf'}


In [139]:
print("Classification Report for SVM:""\n",metrics.classification_report(y_test, y_pred))

Classification Report for SVM:
               precision    recall  f1-score   support

           0       0.84      0.92      0.88      1580
           1       0.66      0.48      0.56       530

    accuracy                           0.81      2110
   macro avg       0.75      0.70      0.72      2110
weighted avg       0.79      0.81      0.80      2110



# DECISION TREE

In [140]:
from sklearn.tree import DecisionTreeClassifier


clf = DecisionTreeClassifier(criterion = "gini", random_state = 5)

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [141]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.7132701421800948


In [142]:
print("Classification Report for Decision Tree:""\n",metrics.classification_report(y_test, y_pred))

Classification Report for Decision Tree:
               precision    recall  f1-score   support

           0       0.82      0.79      0.81      1580
           1       0.44      0.48      0.46       530

    accuracy                           0.71      2110
   macro avg       0.63      0.64      0.63      2110
weighted avg       0.72      0.71      0.72      2110



# RANDOM FOREST

In [143]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators = 10, random_state = 9)
rf.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=9)

In [144]:
predictors = rf.predict(X_train)

In [145]:
y_test

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [146]:
predictors

array([0.6, 1. , 0.2, ..., 0.8, 0.2, 0.7])

In [147]:

cm = metrics.confusion_matrix(y_test, y_pred) 
print(cm)
accuracy = metrics.accuracy_score(y_test, y_pred) 
print("Accuracy score:",accuracy)
precision = metrics.precision_score(y_test, y_pred) 
print("Precision score:",precision)
recall = metrics.recall_score(y_test, y_pred) 
print("Recall score:",recall)

print("Classification Report for Random Forest:""\n",metrics.classification_report(y_test, y_pred))

[[1250  330]
 [ 275  255]]
Accuracy score: 0.7132701421800948
Precision score: 0.4358974358974359
Recall score: 0.4811320754716981
Classification Report for Random Forest:
               precision    recall  f1-score   support

           0       0.82      0.79      0.81      1580
           1       0.44      0.48      0.46       530

    accuracy                           0.71      2110
   macro avg       0.63      0.64      0.63      2110
weighted avg       0.72      0.71      0.72      2110



# Compare Average Accuricies of Different Classifiers


In [149]:
# Step 4 - Compare Classification Algorithms
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

classification_models = []
classification_models.append(('Logistic Regression', LogisticRegression(solver = 'liblinear')))
classification_models.append(('K Nearest Neighbor', KNeighborsClassifier(n_neighbors=9, metric="minkowski",p=2)))
classification_models.append(('Kernel SVM', SVC(kernel = 'rbf', gamma = 0.1)))

classification_models.append(('Naive Bayes', GaussianNB()))
classification_models.append(('Decision Tree', DecisionTreeClassifier(criterion = "entropy")))
classification_models.append(('Random Forest', RandomForestClassifier(n_estimators=100, criterion="entropy")))


for name, model in classification_models:
    kfold = KFold(n_splits=10, random_state=None)
    result = cross_val_score(model, x , y, cv=kfold, scoring='accuracy')
    print(result.mean())



0.8020474346954611
0.7650697497736971
0.8004841264709686
0.7662097504202767
0.7396153255528255
0.794080765873529
